import esbuild from "esbuild";
import process from "node:process";

const production = process.argv[2] === "production";

await esbuild.build({
  entryPoints: ["src/main.ts"],
  bundle: true,
  external: ["obsidian", "electron"],
  format: "cjs",
  target: "es2020",
  minify: production,
  sourcemap: production ? false : "inline",
  outfile: "main.js",
  banner: {
    js: "/* Generated by esbuild. Source: obsidian-file-explorer-split */",
  },
  logLevel: "info",
});
